export const colorPalettes = {
  default: {
    primary: 'text-blue-600',
    secondary: 'text-gray-400',
    accent: 'text-blue-500',
    text: 'text-gray-800',
    border: 'border-gray-300',
    bg: 'bg-white',
  },
  professional: {
    primary: 'text-indigo-700',
    secondary: 'text-slate-500',
    accent: 'text-indigo-600',
    text: 'text-slate-800',
    border: 'border-slate-300',
    bg: 'bg-slate-50',
  },
  creative: {
    primary: 'text-purple-600',
    secondary: 'text-amber-500',
    accent: 'text-purple-500',
    text: 'text-gray-800',
    border: 'border-gray-300',
    bg: 'bg-white',
  },
  modern: {
    primary: 'text-teal-600',
    secondary: 'text-cyan-400',
    accent: 'text-teal-500',
    text: 'text-zinc-800',
    border: 'border-zinc-300',
    bg: 'bg-zinc-50',
  },
  minimal: {
    primary: 'text-stone-700',
    secondary: 'text-stone-400',
    accent: 'text-stone-600',
    text: 'text-neutral-800',
    border: 'border-neutral-300',
    bg: 'bg-white',
  },
  vibrant: {
    primary: 'text-fuchsia-600',
    secondary: 'text-pink-400',
    accent: 'text-fuchsia-500',
    text: 'text-gray-900',
    border: 'border-pink-300',
    bg: 'bg-white',
  },
  elegant: {
    primary: 'text-emerald-600',
    secondary: 'text-gray-500',
    accent: 'text-emerald-500',
    text: 'text-gray-800',
    border: 'border-gray-300',
    bg: 'bg-white',
  },
  bold: {
    primary: 'text-red-600',
    secondary: 'text-orange-500',
    accent: 'text-red-500',
    text: 'text-gray-900',
    border: 'border-gray-300',
    bg: 'bg-white',
  },
  calm: {
    primary: 'text-sky-600',
    secondary: 'text-blue-400',
    accent: 'text-sky-500',
    text: 'text-slate-800',
    border: 'border-slate-300',
    bg: 'bg-white',
  },
  luxury: {
    primary: 'text-violet-700',
    secondary: 'text-purple-500',
    accent: 'text-violet-600',
    text: 'text-gray-900',
    border: 'border-gray-300',
    bg: 'bg-white',
  },
};
