
export const languages = {
  en: {
    aboutMe: 'About Me',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    projects: 'Projects',
    certifications: 'Certifications',
    languages: 'Languages',
    interests: 'Interests',
    socialClubs: 'Social Clubs',
    expertise: 'Expertise',
    contact: 'Contact',
    portfolio: 'Portfolio',
    phone: 'Phone',
    email: 'Email',
    location: 'Location',
    duration: 'Duration',
    institution: 'Institution',
    degree: 'Degree',
    field: 'Field',
    company: 'Company',
    role: 'Role',
    achievements: 'Achievements',
    description: 'Description',
    techStack: 'Tech Stack',
    issuer: 'Issuer',
    year: 'Year',
    level: 'Level'
  },
  fr: {
    aboutMe: 'Profil',
    experience: 'Expérience Professionnelle',
    education: 'Formation',
    skills: 'Compétences',
    projects: 'Projets',
    certifications: 'Certifications',
    languages: 'Langues',
    interests: 'Centres d\'Intérêt',
    socialClubs: 'Activités Extra-professionnelles',
    expertise: 'Expertise',
    contact: 'Contact',
    portfolio: 'Portfolio',
    phone: 'Téléphone',
    email: 'Email',
    location: 'Localisation',
    duration: 'Durée',
    institution: 'Établissement',
    degree: 'Diplôme',
    field: 'Domaine',
    company: 'Entreprise',
    role: 'Poste',
    achievements: 'Réalisations',
    description: 'Description',
    techStack: 'Technologies Utilisées',
    issuer: 'Organisme',
    year: 'Année',
    level: 'Niveau'
  },
  ar: {
    aboutMe: 'نبذة عني',
    experience: 'الخبرة العملية',
    education: 'التعليم',
    skills: 'المهارات',
    projects: 'المشاريع',
    certifications: 'الشهادات',
    languages: 'اللغات',
    interests: 'الاهتمامات',
    socialClubs: 'النشاطات الاجتماعية',
    expertise: 'الخبرات',
    contact: 'للتواصل',
    portfolio: 'المحفظة',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    location: 'الموقع',
    duration: 'المدة',
    institution: 'المؤسسة',
    degree: 'الدرجة العلمية',
    field: 'التخصص',
    company: 'الشركة',
    role: 'المنصب',
    achievements: 'الإنجازات',
    description: 'الوصف',
    techStack: 'التقنيات المستخدمة',
    issuer: 'الجهة المانحة',
    year: 'السنة',
    level: 'المستوى'
  }
};

